### ISSUE TITLE
LatticeECP3 Versa Dev kit

### ISSUE THREAD

**Issue by dine909** [dawsonjon/FPGA-TX#1]
Hi there Jonathan,
   Loving your work, I have a few LatticeECP3 Versa Dev kits spare, would you like one for this kind of thing? The specs mention that SERDES can reach up to 3.2GHz.. and SMA's!

Let me know.

Cheers

http://www.latticesemi.com/-/media/LatticeSemi/Documents/ApplicationNotes/L/AM/LatticeECP3SERDESPCSUsageGuide.ashx?document_id=32316

http://www.latticesemi.com/ecp3versa

**Comment by dawsonjon** [comment]
Hi,

Thanks very much for your interest in my project. Thanks also for your kind offer. I will decline if you don't mind - I don't think I can spare enough time at the moment.

Kind Regards
Jon

**Comment by dine909** [comment]
Know the feeling!

Cheers.
